// Sources/SwiflowEmbedders/DriverEmbedder.swift
//
// THE emit path for EmbeddedDriver.swift — invoked by the swiflow-codegen
// tool (`swift run swiflow-codegen driver`), which replaced the standalone
// script that used to re-implement this inline. The byte-pin test in
// Tests/SwiflowCLITests/DriverEmbedderTests.swift asserts the tracked
// EmbeddedDriver.swift is bit-for-bit this function's output.

import Foundation

package enum DriverEmbedder {
    /// Produces the Swift source for `EmbeddedDriver.swift` that wraps the
    /// readable JS sources and their esbuild-minified variants as raw string
    /// literals.
    ///
    /// We use Swift's extended-delimiter raw string (`#"""..."""#`) so that
    /// any quotes, backslashes, or string-interpolation markers in the JS
    /// source pass through untouched. The JS driver currently contains
    /// neither `"""#` nor `#"""`, but defensively bumping to `##"""..."""##`
    /// would be wise if a future JS edit ever introduced one.
    package static func swiftSource(
        driverJS: String, driverJSMinified: String,
        swJS: String, swJSMinified: String,
        regionsJS: String, regionsJSMinified: String,
        guestSdkJS: String, guestSdkJSMinified: String
    ) -> String {
        // Swift multi-line strings strip ONE newline immediately after the
        // opening delimiter and ONE immediately before the closing delimiter.
        // So to round-trip a JS source `V` (which itself ends in `\n`)
        // verbatim, the literal between `#"""` and `"""#` must be
        // `\n` + V + `\n`. We achieve that by interpolating `\(...)` on its
        // own line and putting `"""#` on the next line — the trailing `\n`
        // of the source lands inside the raw-string body, and the next `\n`
        // (the one that ends the interpolation line) is the one Swift strips.
        // The minified variants are produced by esbuild (--minify) and also
        // end in a trailing newline for uniform raw-string wrapping.
        return """
        // GENERATED FILE — do not edit.
        //
        // Regenerate by running, from the repo root:
        //     swift run swiflow-codegen driver
        //
        // Source: js-driver/swiflow-driver.js + js-driver/swiflow-service-worker.js + js-driver/swiflow-regions.js + js-driver/swiflow-region-guest.js
        // Minified variants generated by esbuild (--minify).

        enum EmbeddedDriver {
            static let javascriptSource: String = #\"\"\"
        \(driverJS)
        \"\"\"#

            static let javascriptSourceMinified: String = #\"\"\"
        \(driverJSMinified)
        \"\"\"#

            static let serviceWorkerSource: String = #\"\"\"
        \(swJS)
        \"\"\"#

            static let serviceWorkerSourceMinified: String = #\"\"\"
        \(swJSMinified)
        \"\"\"#

            static let regionsSource: String = #\"\"\"
        \(regionsJS)
        \"\"\"#

            static let regionsSourceMinified: String = #\"\"\"
        \(regionsJSMinified)
        \"\"\"#

            static let guestSdkSource: String = #\"\"\"
        \(guestSdkJS)
        \"\"\"#

            static let guestSdkSourceMinified: String = #\"\"\"
        \(guestSdkJSMinified)
        \"\"\"#
        }
        """ + "\n"
    }
}
