// Tests/SwiflowCLITests/DriverEmbedderTests.swift
import Foundation
import Testing
@testable import SwiflowCLI

@Suite("Driver embedding")
struct DriverEmbedderTests {

    @Test("DriverEmbedder.swiftSource wraps the JS source in a Swift String constant")
    func wrapsJSAsSwiftConstant() {
        let js = "console.log('hello');"
        let generated = DriverEmbedder.swiftSource(forJSSource: js)
        #expect(generated.contains("// GENERATED FILE — do not edit."))
        #expect(generated.contains("enum EmbeddedDriver"))
        #expect(generated.contains("static let javascriptSource: String"))
        // The JS source must appear verbatim somewhere in the output.
        #expect(generated.contains(js))
    }

    @Test("EmbeddedDriver.javascriptSource matches js-driver/swiflow-driver.js verbatim")
    func embeddedDriverIsFresh() throws {
        // Resolve js-driver/swiflow-driver.js relative to this test file so
        // the test works from any CWD.
        let testFile = URL(fileURLWithPath: #filePath)
        let repoRoot = testFile
            .deletingLastPathComponent()  // SwiflowCLITests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // repo root
        let driverURL = repoRoot.appendingPathComponent("js-driver/swiflow-driver.js")

        let onDiskJS = try String(contentsOf: driverURL, encoding: .utf8)
        #expect(EmbeddedDriver.javascriptSource == onDiskJS, """
            EmbeddedDriver is stale. Regenerate by running:
                swift scripts/embed-driver.swift
            from the repo root, then commit Sources/SwiflowCLI/EmbeddedDriver.swift.
            """)
    }

    @Test("EmbeddedDriver contains dev error handler and RAF shim")
    func containsDevErrorHandlerAndRAFShim() {
        #expect(EmbeddedDriver.javascriptSource.contains("__swiflowDevError"))
        #expect(EmbeddedDriver.javascriptSource.contains("[swiflow dev] For Swift source locations"))
        #expect(EmbeddedDriver.javascriptSource.contains("goo.gle/wasm-debugging-extension"))
    }

    @Test("EmbeddedDriver.swift is bit-for-bit what DriverEmbedder would produce")
    func embeddedDriverMatchesDriverEmbedderOutput() throws {
        // Catches drift between scripts/embed-driver.swift and
        // DriverEmbedder.swiftSource — if someone edits the wrapping logic
        // in one place without the other, the committed EmbeddedDriver.swift
        // (most recently generated by the script) will differ from what
        // DriverEmbedder would produce now.
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // SwiflowCLITests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // repo root
        let jsURL = repoRoot
            .appendingPathComponent("js-driver/swiflow-driver.js")
        let embeddedURL = repoRoot
            .appendingPathComponent("Sources/SwiflowCLI/EmbeddedDriver.swift")

        let jsSource = try String(contentsOf: jsURL, encoding: .utf8)
        let expectedEmbedded = DriverEmbedder.swiftSource(forJSSource: jsSource)
        let actualEmbedded = try String(contentsOf: embeddedURL, encoding: .utf8)

        #expect(actualEmbedded == expectedEmbedded, """
            EmbeddedDriver.swift drifted from DriverEmbedder.swiftSource output. \
            Run `swift scripts/embed-driver.swift` and check the script/library \
            produce the same wrapping format.
            """)
    }
}
